Exercise
--------

Exercise
--------

A taste of things to come
=========================

In this exercise, you'll explore both the _Non-Pythonic_ and _Pythonic_ ways of looping over a list.

    names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
    

Suppose you wanted to collect the names in the above list that have six letters or more. In other programming languages, the typical approach is to create an index variable (`i`), use `i` to iterate over the list, and use an if statement to collect the names with six letters or more:

    i = 0
    new_list= []
    while i < len(names):
        if len(names[i]) >= 6:
            new_list.append(names[i])
        i += 1
    

Let's explore some more _Pythonic_ ways of doing this.

Instructions 1/3
----------------

*    Print the list, `new_list`, that was created using a _Non-Pythonic_ approach.
    
*   A more _Pythonic_ approach would loop over the contents of `names`, rather than using an index variable. Print `better_list`.
    
*   The best _Pythonic_ way of doing this is by using list comprehension. Print `best_list`.

In [2]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']


# Print the list created using the Non-Pythonic approach
i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

# Print the list created by looping over the contents of names
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

# Print the list created by using list comprehension
best_list = [name for name in names if len(name) >= 6]
print(best_list)


['Kramer', 'Elaine', 'George', 'Newman']
['Kramer', 'Elaine', 'George', 'Newman']
['Kramer', 'Elaine', 'George', 'Newman']


Zen of Python
=============

In the video, we covered the _Zen of Python_ written by Tim Peters, which lists 19 idioms that serve as guiding principles for any Pythonista. Python has hundreds of _Python Enhancement Proposals_, commonly referred to as _PEPs_. The _Zen of Python_ is one of these _PEPs_ and is documented as [PEP20](https://www.python.org/dev/peps/pep-0020/).

One little Easter Egg in Python is the ability to print the _Zen of Python_ using the command `import this`. Let's take a look at one of the idioms listed in these guiding principles.

Type and run the command `import this` within your IPython console and answer the following question:


### Instructions

What is the 7th idiom of the Zen of Python?

#### Possible answers

* Flat is better than nested.

* Beautiful is better than ugly.

* Readability counts. <--->

* Python is the best programming language ever.


Built-in practice: range()
==========================

In this exercise, you will practice using Python's built-in function `range()`. Remember that you can use `range()` in a few different ways:

**1)** Create a sequence of numbers from 0 to a stop value (which is _exclusive_). This is useful when you want to create a simple sequence of numbers starting at zero:

    range(stop)
    
    # Example
    list(range(11))
    
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    

**2)** Create a sequence of numbers from a start value to a stop value (which is _exclusive_) with a step size. This is useful when you want to create a sequence of numbers that increments by some value other than one. For example, a list of even numbers:

    range(start, stop, step)
    
    # Example
    list(range(2,11,2))
    
    [2, 4, 6, 8, 10]
    
### Instructions

*   Create a _range object_ that starts at zero and ends at five. Only use a `stop` argument.
*   Convert the `nums` variable into a list called `nums_list`.
*   Create a new list called `nums_list2` that starts at **one**, ends at **eleven**, and increments by **two** by unpacking a _range object_ using the star character (`*`).


In [ ]:
# Create a range object that goes from 0 to 5
nums = range(0,6)
print(type(nums))

# Convert nums to a list
nums_list = list(nums)
print(nums_list)

# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]
print(nums_list2)

Built-in practice: enumerate()
==============================

In this exercise, you'll practice using Python's built-in function`enumerate()`. This function is useful for obtaining an indexed list. For example, suppose you had a list of people that arrived at a party you are hosting. The list is ordered by arrival (Jerry was the first to arrive, followed by Kramer, etc.):

    names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
    

If you wanted to attach an index representing a person's arrival order, you_could_use the following for loop:

    indexed_names = []
    for i in range(len(names)):
        index_name = (i, names[i])
        indexed_names.append(index_name)
    
    [(0,'Jerry'),(1,'Kramer'),(2,'Elaine'),(3,'George'),(4,'Newman')]
    

But, that's not the most efficient solution. Let's explore how to use`enumerate()`to make this more efficient.

Instructions
------------

100 XP

*   Instead of using `for i in range(len(names))`, update the for loop to use`i`as the index variable and`name`as the iterator variable and use`enumerate()`.
*   Rewrite the previous for loop using `enumerate()` and list comprehension to create a new list,`indexed_names_comp`.
*   Create another list (`indexed_names_unpack`) by using the star character (`*`) to unpack the_enumerate object_created from using`enumerate()`on`names`. This time, **start the index for** `enumerate()` **at one instead of zero.**

Take Hint (-30 XP)

In [13]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [14]:
# Rewrite the for loop to use enumerate
indexed_names = []
for i in range(len(names)):
    for name in names:
        index_name = (i,name)
        indexed_names.append(index_name) 
print(indexed_names)

# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

[(0, 'Jerry'), (0, 'Kramer'), (0, 'Elaine'), (0, 'George'), (0, 'Newman'), (1, 'Jerry'), (1, 'Kramer'), (1, 'Elaine'), (1, 'George'), (1, 'Newman'), (2, 'Jerry'), (2, 'Kramer'), (2, 'Elaine'), (2, 'George'), (2, 'Newman'), (3, 'Jerry'), (3, 'Kramer'), (3, 'Elaine'), (3, 'George'), (3, 'Newman'), (4, 'Jerry'), (4, 'Kramer'), (4, 'Elaine'), (4, 'George'), (4, 'Newman')]
[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]
[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


Built-in practice: map()
========================

In this exercise, you'll practice using Python's built-in `map()` function to apply a function to every element of an object. Let's look at a list of party guests:

    names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
    

Suppose you wanted to create a new list (called `names_uppercase`) that converted all the letters in each name to uppercase. you could accomplish this with the below for loop:

    names_uppercase = []
    
    for name in names:
      names_uppercase.append(name.upper())
    
    ['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']
    

Let's explore using the `map()` function to do this more efficiently in one line of code.

### Instructions

*   Use `map()` and the method `str.upper()` to convert each name in the list `names` to uppercase. Save this to the variable `names_map`.
*   Print the data type of `names_map`.
*   Unpack the contents of `names_map` into a list called `names_uppercase` using the star character (`*`).
*   Print `names_uppercase` and observe its contents.

In [ ]:
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Print the type of the names_map
print(type(names_map))

# Unpack names_map into a list
names_uppercase = [*names_map]

# Print the list created above
print(names_uppercase)

Practice with NumPy arrays
==========================

Let's practice slicing `numpy` arrays and using NumPy's broadcasting concept. Remember, broadcasting refers to a `numpy` array's ability to vectorize operations, so they are performed on all elements of an object at once.

A two-dimensional `numpy` array has been loaded into your session (called `nums`) and printed into the console for your convenience. `numpy` has been imported into your session as `np`.

### Instructions 1/2

*   Print the second row of `nums`.
*   Print the items of `nums` that are greater than six.
*   Create `nums_dbl` that doubles each number in `nums`.
*   Replace the third column in `nums` with a new column that adds `1` to each item in the original column.



Practice with NumPy arrays
==========================

Let's practice slicing `numpy` arrays and using NumPy's broadcasting concept. Remember, broadcasting refers to a `numpy` array's ability to vectorize operations, so they are performed on all elements of an object at once.

A two-dimensional `numpy` array has been loaded into your session (called `nums`) and printed into the console for your convenience. `numpy` has been imported into your session as `np`.

### Instructions 1/2

*   Print the second row of `nums`.
*   Print the items of `nums` that are greater than six.
*   Create `nums_dbl` that doubles each number in `nums`.
*   Replace the third column in `nums` with a new column that adds `1` to each item in the original column.

In [7]:
import numpy as np

nums = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [8]:
# Print second row of nums
print(nums[1,:])

# Print all elements of nums that are greater than six
print(nums[nums > 6])

# Double every element of nums
nums_dbl = nums * 2
print(nums_dbl)

# Replace the third column of nums
nums[:,2] = nums[:,2] + 1
print(nums)

[ 6  7  8  9 10]
[ 7  8  9 10]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


Practice with NumPy arrays
==========================

Let's practice slicing `numpy` arrays and using NumPy's broadcasting concept. Remember, broadcasting refers to a `numpy` array's ability to vectorize operations, so they are performed on all elements of an object at once.

A two-dimensional `numpy` array has been loaded into your session (called `nums`) and printed into the console for your convenience. `numpy` has been imported into your session as `np`.

Instructions 2/2

Question


When compared to a list object, what are two advantages of using a `numpy` array?

### Possible answers

A `numpy` array is the only data structure that can be used with the `numpy` package and often has less verbose indexing syntax.

A `numpy` array contains homogeneous data types (which reduces memory consumption) and provides the ability to apply operations on all elements through broadcasting. <--->

A `numpy` array supports boolean indexing and has much better one-dimensional indexing capabilities.

Both a list object and a `numpy` array are identical.

Bringing it all together: Festivus!
===================================

In this exercise, you will be throwing a party—a Festivus if you will!

You have a list of guests (the `names` list). Each guest, for whatever reason, has decided to show up to the party in 10-minute increments. For example, Jerry shows up to Festivus 10 minutes into the party's start time, Kramer shows up 20 minutes into the party, and so on and so forth.

We want to write a few simple lines of code, using the built-ins we have covered, to welcome each of your guests and let them know how many minutes late they are to your party. Note that `numpy` has been imported into your session as `np` and the `names` list has been loaded as well.

Let's welcome your guests!

### Instructions 1/4


*   Use `range()` to create a list of arrival times (10 through 50 incremented by 10). Create the list `arrival_times` by unpacking the _range object_.

In [9]:
# Create a list of arrival times
arrival_times = [*range(10, 51, 10)]

print(arrival_times)

[10, 20, 30, 40, 50]


### Instructions 2/4

*   You realize your clock is three minutes fast. Convert the `arrival_times` list into a `numpy` array (called `arrival_times_np`) and use NumPy broadcasting to subtract three minutes from each arrival time.

In [10]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

print(new_times)

[ 7 17 27 37 47]


### Instructions 3/4

*   Use list comprehension with `enumerate()` to pair each guest in the `names` list to their updated arrival time in the `new_times` array. You'll need to use the index variable created from using `enumerate()` on `new_times` to index the `names` list.

In [11]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


### Instructions 4/4

*   A function named `welcome_guest()` has been pre-loaded into your session. Use `map()` to apply this function to each element of the `guest_arrivals` list and save it as the variable `welcome_map`.

In [16]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

def welcome_guest(guest, time):
    # Calculate the lateness
    lateness = max(time - 5, 0)  # Assuming the event starts at time 5

    # Generate the welcome message
    message = f"Welcome to Festivus {guest}... You're {lateness} min late."

    return message

In [17]:
# Create a list of arrival times
arrival_times = [*range(10,60,10)]

# Convert arrival_times to an array and update the times
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

# Use list comprehension and enumerate to pair guests to new times
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

# Map the welcome_guest function to each (guest,time) pair
welcome_map = map(welcome_guest, guest_arrivals)

guest_welcomes = [*welcome_map]
print(*guest_welcomes, sep='\n')

TypeError: welcome_guest() missing 1 required positional argument: 'time'

Using %timeit: your turn!
=========================

You'd like to create a list of integers from 0 to 50 using the `range()` function. However, you are unsure whether using list comprehension or unpacking the _range object_ into a list is faster. Let's use `%timeit` to find the best implementation.

For your convenience, a reference table of time orders of magnitude is provided below (faster at the top).

Instructions 1/3

*   Use list comprehension and `range()` to create a list of integers from 0 to 50 called `nums_list_comp`.

Take Hint (-10 XP)

In [18]:
# Create a list of integers (0-50) using list comprehension
nums_list_comp = [num for num in range(51)]
print(nums_list_comp)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


Instructions 2/3

*   Use `range()` to create a list of integers from 0 to 50 and unpack its contents into a list called `nums_unpack`.

In [19]:
# Create a list of integers (0-50) using list comprehension
nums_list_comp = [num for num in range(51)]
print(nums_list_comp)

# Create a list of integers (0-50) by unpacking range
nums_unpack = [*range(51)]
print(nums_unpack)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


Question
--------

Use `%timeit` **within your IPython console** (i.e. **not** within the script.py window) to compare the runtimes for creating a list of integers from 0 to 50 using list comprehension vs. unpacking the _range object_. Don't include the `print()` statements when timing.

**Which method was faster?**

### Possible answers

*   List comprehension was faster than unpacking `range()`.

*   Unpacking the _range object_ was faster than list comprehension. <--->

*   Both methods had the same runtime.



In [2]: %timeit nums_list_comp = [num for num in range(51)]

    2.64 us +- 116 ns per loop (mean +- std. dev. of 7 runs, 100000 loops each)

In [3]:

    %timeit nums_unpack = [*range(51)]

Using %timeit: specifying number of runs and loops
==================================================

A list of 480 superheroes has been loaded into your session (called `heroes`). You'd like to analyze the runtime for converting this `heroes` list into a set. Instead of relying on the default settings for `%timeit`, you'd like to only use 5 runs and 25 loops per each run.

**What is the correct syntax when using `%timeit` and only using 5 runs with 25 loops per each run?**

Instructions

### Possible answers

-   `timeit -runs5 -loops25 set(heroes)`

-   `%%timeit -r5 -n25 set(heroes)`

-   `%timeit set(heroes), 5, 25`

-   `%timeit -r5 -n25 set(heroes)` <--->

Correct! `%timeit` lets you specify the number of runs and number of loops you want to consider with the `-r` and `-n` flags. You can use `-r5` and `-n25` to specify 5 iterations each with 25 loops when calculating the average and standard deviation of runtime for your code.

Using %timeit: formal name or literal syntax
============================================

Python allows you to create data structures using **either** a _formal name_ or a _literal syntax_. In this exercise, you'll explore how using a _literal syntax_ for creating a data structure can speed up runtimes.

<table>
<thead>
<tr>
<th>data structure</th>
<th>formal name</th>
<th>literal syntax</th>
</tr>
</thead>
<tbody>
<tr>
<td>list</td>
<td><code>list()</code></td>
<td><code>[]</code></td>
</tr>
<tr>
<td>dictionary</td>
<td><code>dict()</code></td>
<td><code>{}</code></td>
</tr>
<tr>
<td>tuple</td>
<td><code>tuple()</code></td>
<td><code>()</code></td>
</tr>
</tbody>
</table>

### Instructions 1/3

*   Create an empty list called `formal_list` using the formal name (`list()`).
*   Create an empty list called `literal_list` using the literal syntax (`[]`).

In [20]:
# Create a list using the formal name
formal_list = list()
print(formal_list)

# Create a list using the literal syntax
literal_list = []
print(literal_list)

[]
[]


### Instructions 2/3

*   Print out the type of `formal_list` and `literal_list` to show that both naming conventions create a list.


In [21]:
# Create a list using the formal name
formal_list = list()
print(formal_list)

# Create a list using the literal syntax
literal_list = []
print(literal_list)

# Print out the type of formal_list
print(type(list()))

# Print out the type of literal_list
print(type([]))

[]
[]
<class 'list'>
<class 'list'>


### Instructions 3/3

#### Question

Use `%timeit` **in your IPython console** to compare runtimes between creating a list using the formal name (`list()`) and the literal syntax (`[]`). Don't include the `print()` statements when timing.

**Which naming convention is faster?**

#### Possible answers

-   Using the formal name (`list()`) to create a list is faster.

-   Using the literal syntax (`[]`) to create a list is faster. <--->

-   Both naming conventions have the same runtime.


Output:

In [1]: %timeit literal_list = list()

    101 ns +- 9.26 ns per loop (mean +- std. dev. of 7 runs, 10000000 loops each)

In [2]: %timeit literal_list = []

    47 ns +- 0.691 ns per loop (mean +- std. dev. of 7 runs, 10000000 loops each)


Great job! Using Python's literal syntax to define a data structure can speed up your runtime. Consider using the literal syntaxes (like [] instead of list(), {} instead of dict(), or () instead of tuple()), where applicable, to gain some speed.
    

Using cell magic mode (%%timeit)
================================

From here on out, you'll be working with a superheroes dataset. For this exercise, a list of each hero's weight in kilograms (called `wts`) is loaded into your session. You'd like to convert these weights into pounds.

You could accomplish this using the below for loop:

    hero_wts_lbs = []
    for wt in wts:
        hero_wts_lbs.append(wt * 2.20462)
    

Or you could use a `numpy` array to accomplish this task:

    wts_np = np.array(wts)
    hero_wts_lbs_np = wts_np * 2.20462
    

Use `%%timeit` **in your IPython console** to compare runtimes between these two approaches. Make sure to press `SHIFT+ENTER` after the magic command to add a new line before writing the code you wish to time. After you've finished coding, answer the following question:

**Which of the above techniques is faster?**

### Instructions

#### Possible answers

The for loop technique was faster.

**The `numpy` technique was faster.**

Both techniques had similar runtimes.